# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: amedvede <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/09 13:23:02 by amedvede          #+#    #+#              #
#    Updated: 2018/08/09 17:34:10 by amedvede         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
F_NAME = ft_display_file.c

all: $(NAME)

$(NAME):

	gcc -Wall -Werror -Wextra -o $(NAME) $(F_NAME)

clean:
	/bin/rm -f $(NAME)

fclean: clean
