# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: amedvede <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/09 17:52:00 by amedvede          #+#    #+#              #
#    Updated: 2018/08/09 17:56:26 by amedvede         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

EX = ft_cat.c
NAME = ft_cat

all: $(NAME)

$(NAME):

	gcc -Wall -Werror -Wextra -o $(NAME) $(EX)

clean:
	/bin/rm -f $(NAME)

fclean: clean
